#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import logging, logging.handlers
import sys
import time


# local logger
mylogger = logging.getLogger("local")
myformatter = logging.Formatter("%(filename)s: %(levelname)s: %(message)s")
myhandler = logging.StreamHandler()
myhandler.setFormatter(myformatter)
mylogger.addHandler(myhandler)

# argparse
parser = argparse.ArgumentParser(
        description="the stupid syslog sender",
        epilog="https://github.com/ypsun/logsend"
        )
parser.add_argument("-f", "--eps", type=int, default=1, help="events per second (eps) ")
parser.add_argument("-i", "--file", type=argparse.FileType("r"), help="message by file content")
parser.add_argument("-n", "--number", type=int, metavar="N", default=1, help="send %(metavar)s events, -1 for endless")
parser.add_argument("-s", "--server", default="localhost", metavar="SERVER", help="send to syslog server %(metavar)s")
parser.add_argument("-v", "--version", action="version", version="1.0")
parser.add_argument("message", help="message by text")
args = parser.parse_args()


# [ initialization ]
# logger to work
logger = logging.getLogger("logsend")
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())
logger.addHandler(logging.handlers.SysLogHandler(address=(args.server, 514)))
# other
period = 1.0 / args.eps
msg = (line.rstrip() for line in args.file) if args.file else (args.message for i in xrange(args.number))
runs = iter(int, 1) if args.file or args.number < 0 else xrange(args.number)


# [ main ]
try:
    for run in runs:
        # TODO: facility.severity should be add here -- Fri Aug 29 05:56:45 UTC 2014 by ypsun
        logger.debug(msg.next())
        time.sleep(period)
except StopIteration:
    pass
