#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import itertools
import logging, logging.handlers
import time


# local logger
mylogger = logging.getLogger("local")
myformatter = logging.Formatter("%(filename)s: %(levelname)s: %(message)s")
myhandler = logging.StreamHandler()
myhandler.setFormatter(myformatter)
mylogger.addHandler(myhandler)

# argparse
def pri_type(priority):
    facility = ["auth", "authpriv", "cron", "daemon", "ftp", "kern", "lpr", "mail", "news", "syslog", "user", "uucp", \
                "local0", "local1", "local2", "local3", "local4", "local5", "local6", "local7"]
    severity = ["debug", "info", "warning", "error", "critical"]
    f, s = priority.split(".")
    if f not in facility:
        raise argparse.ArgumentTypeError("unknown facility name: %s\nsupported are %s" % (f, facility))
    if s not in severity:
        raise argparse.ArgumentTypeError("unknown severity name: %s\nsupported are %s" % (s, severity))
    return f, s

parser = argparse.ArgumentParser(
        description="the stupid syslog sender",
        epilog="https://github.com/ypsun/logsend"
        )
parser.add_argument("-f", "--eps", type=int, default=1, help="events per second (eps) ")
parser.add_argument("-i", "--file", type=argparse.FileType("r"), help="message by file content")
parser.add_argument("-n", "--number", type=int, metavar="N", help="send %(metavar)s events, -1 for endless")
parser.add_argument("-p", "--priority", type=pri_type, default="syslog.info", help="syslog priority (facility.severity)")
parser.add_argument("-s", "--server", default="localhost", metavar="SERVER", help="send to syslog server %(metavar)s")
parser.add_argument("-v", "--version", action="version", version="1.0")
parser.add_argument("message", nargs="?", help="message by text")
args = parser.parse_args()


# [ initialization ]
# -f
period = 1.0 / args.eps
# -i and message
msg = (line.rstrip() for line in args.file) if args.file else (args.message for i in itertools.count())
# -n
if args.message and args.number is None:
    args.number = 1
runs = xrange(args.number) if args.number >= 0 else itertools.count()
# -p
facility, severity = args.priority
# logger to work
logger = logging.getLogger("logsend")
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())
logger.addHandler(logging.handlers.SysLogHandler(address=(args.server, 514), facility=facility))
exec("logsend = logger.%s" % severity)


# [ main ]
try:
    for run in runs:
        logsend(msg.next())
        time.sleep(period)
except StopIteration:
    pass
